G_MW: 360
H2_storage_capex_cost: 300
H2_storage_opex_cost: 3
H2_transportation_cost: 5
H2_transportation_distance: 0
N_life: 25
altitude: null
battery_BOP_installation_commissioning_cost: 80000
battery_WACC: 0.06
battery_charge_efficiency: 0.985
battery_control_system_cost: 2250
battery_depth_of_discharge: 0.9
battery_energy_cost: 62000
battery_energy_onm_cost: 0
battery_power_cost: 16000
battery_price_reduction_per_year: 0.1
bi_directional_status: 0
d_ref: 145
depreciation:
- 0
- 1
depreciation_yr:
- 0
- 25
electrolyzer_capex_cost: 800000
electrolyzer_eff_curve_name: PEM electrolyzer H2 production
electrolyzer_eff_curve_type: production
electrolyzer_opex_cost: 16000
electrolyzer_power_electronics_cost: 0
elevation_fn: /groups/INP/era5/SRTMv3_plus_ViewFinder_coarsen.nc
era5_ghi_zarr: /groups/INP/era5/ghi.zarr
era5_zarr: /groups/reanalyses/era5/app/era5.zarr
hh_ref: 100
hhv: 39.3
hpp_BOS_soft_cost: 119940
hpp_grid_connection_cost: 50000
inflation:
- 0.1
- 0.1
- 0.06
- 0.06
inflation_yr:
- -3
- 0
- 1
- 25
land_cost: 300000
land_use_per_solar_MW: 0.01226
latitude: null
longitude: null
min_LoH: 0.7
min_power_standby: 0.0
n_full_power_hours_expected_per_day_at_peak_price: 0
p_rated_ref: 5.0
peak_hr_quantile: 0.9
penalty_BM: 2000
penalty_factor_H2: 0
phasing_CAPEX:
- 1
- 1
phasing_yr:
- -1
- 0
price_H2: 5
ptg_WACC: 0.08
ptg_deg: 0.99
pv_deg:
- 0.03
- 0.03
- 0.28
pv_deg_yr:
- 0
- 1
- 25
ratio_gwa_era5: /groups/INP/era5/ratio_gwa2_era5.nc
ref_yr_inflation: 0
share_WT_deg_types: 0.5
solar_PV_cost: 110000
solar_WACC: 0.06
solar_fixed_onm_cost: 4500
solar_hardware_installation_cost: 100000
solar_inverter_cost: 20000
storage_eff: 0.9
tax_rate: 0.22
tracking: 'No'
water_consumption: 9.4
water_cost: 4
water_treatment_cost: 2
wind_WACC: 0.06
wind_civil_works_cost: 260000
wind_deg:
- 0
- 0.25
wind_deg_yr:
- 0
- 25
wind_fixed_onm_cost: 12600
wind_turbine_cost: 640000
wind_variable_onm_cost: 1.35
wpp_efficiency: 1
year: '2012'
